from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.http import MediaFileUpload

scopes = ["https://www.googleapis.com/auth/youtube.upload"]
flow = InstalledAppFlow.from_client_secrets_file("client_secret.json", scopes)
credentials = flow.run_console()

youtube = build("youtube", "v3", credentials=credentials)
request = youtube.videos().insert(
    part="snippet,status",
    body={
        "snippet": {
            "title": "My Video Title",
            "description": "My Video Description",
            "tags": ["tag1", "tag2"],
            "categoryId": "22"
        },
        "status": {
            "privacyStatus": "private"
        }
    },
    media_body=MediaFileUpload("my_video.mp4")  # Video file path
)
response = request.execute()
print(response)
